/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c NmAdaptor -a src/nm_adaptor.h:src/nm_adaptor.cpp interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "src/nm_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class NmAdaptor
 */

NmAdaptor::NmAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

NmAdaptor::~NmAdaptor()
{
    // destructor
}

int NmAdaptor::executeConfiguration(const QString &config)
{
    // handle method call de.lastlog.nmInterface.executeConfiguration
    int retval;
    QMetaObject::invokeMethod(parent(), "executeConfiguration", Q_RETURN_ARG(int, retval), Q_ARG(QString, config));
    return retval;
}

uint NmAdaptor::listConfigs()
{
    // handle method call de.lastlog.nmInterface.listConfigs
    uint count;
    QMetaObject::invokeMethod(parent(), "listConfigs", Q_RETURN_ARG(uint, count));
    return count;
}

QString NmAdaptor::queryConfigurationName(int pos)
{
    // handle method call de.lastlog.nmInterface.queryConfigurationName
    QString configName;
    QMetaObject::invokeMethod(parent(), "queryConfigurationName", Q_RETURN_ARG(QString, configName), Q_ARG(int, pos));
    return configName;
}

int NmAdaptor::reloadConfigurations()
{
    // handle method call de.lastlog.nmInterface.reloadConfigurations
    int retval;
    QMetaObject::invokeMethod(parent(), "reloadConfigurations", Q_RETURN_ARG(int, retval));
    return retval;
}

