/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c NmAdaptor -a src/nm_adaptor.h:src/nm_adaptor.cpp interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NM_ADAPTOR_H_1259016959
#define NM_ADAPTOR_H_1259016959

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface de.lastlog.nmInterface
 */
class NmAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "de.lastlog.nmInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"de.lastlog.nmInterface\" >\n"
"    <method name=\"reloadConfigurations\" >\n"
"      <arg direction=\"out\" type=\"i\" name=\"retval\" />\n"
"    </method>\n"
"    <method name=\"listConfigs\" >\n"
"      <arg direction=\"out\" type=\"u\" name=\"count\" />\n"
"    </method>\n"
"    <method name=\"executeConfiguration\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"config\" />\n"
"      <arg direction=\"out\" type=\"i\" name=\"retval\" />\n"
"    </method>\n"
"    <method name=\"queryConfigurationName\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"pos\" />\n"
"      <arg direction=\"out\" type=\"s\" name=\"configName\" />\n"
"    </method>\n"
"    <signal name=\"debugOutput\" >\n"
"      <!--       <annotation name=d\"e.lastlog.nmInterface.QtTypeName.Out0\" value=\"infoStruct\"/> -->\n"
"      <arg direction=\"out\" type=\"s\" name=\"message\" />\n"
"      <!--       <arg type=\"s\" name=\"timestamp\" direction=\"out\"/> -->\n"
"      <!--       <arg type=\"s\" name=\"process_name\" direction=\"out\"/> -->\n"
"      <!--       <arg type=\"u\" name=\"process_pid\" direction=\"out\"/> -->\n"
"      <!--       <arg type=\"u\" name=\"stdLevel\" direction=\"out\"/> -->\n"
"    </signal>\n"
"    <signal name=\"crashed\" />\n"
"  </interface>\n"
        "")
public:
    NmAdaptor(QObject *parent);
    virtual ~NmAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int executeConfiguration(const QString &config);
    uint listConfigs();
    QString queryConfigurationName(int pos);
    int reloadConfigurations();
Q_SIGNALS: // SIGNALS
    void crashed();
    void debugOutput(const QString &message);
};

#endif
